// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using N5.Employees.Infrastructure.Persistence.Contexts;

#nullable disable

namespace N5.Employees.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250719085129_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("N5.Employees.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0353e9ac-20b6-4eb5-a052-9d73f7f44d6f"),
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = new Guid("a58ddb18-aacc-4e83-8c64-88f38e8e5d51"),
                            FirstName = "Ronald",
                            LastName = "Reik"
                        },
                        new
                        {
                            Id = new Guid("505c4587-18cb-41dd-be29-455a32dcad6e"),
                            FirstName = "Michael",
                            LastName = "Scout"
                        });
                });

            modelBuilder.Entity("N5.Employees.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateGranted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PermissionTypeId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("N5.Employees.Domain.Entities.PermissionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f650efe9-b39b-462c-b9c3-5639621703f8"),
                            Description = "Paid Vacations"
                        },
                        new
                        {
                            Id = new Guid("fb96b552-7412-4901-a0f8-e2043043c470"),
                            Description = "No Paid Vacations"
                        },
                        new
                        {
                            Id = new Guid("fd5e0995-8d7f-4057-89f3-307c0b48d865"),
                            Description = "Change Schedule"
                        },
                        new
                        {
                            Id = new Guid("8c15fdf5-1b7e-4b35-b7ca-c3dd0d1a0967"),
                            Description = "Remote Work"
                        },
                        new
                        {
                            Id = new Guid("4533dbaf-0dd3-4e05-b128-5a004398171f"),
                            Description = "Study License"
                        });
                });

            modelBuilder.Entity("N5.Employees.Domain.Entities.Permission", b =>
                {
                    b.HasOne("N5.Employees.Domain.Entities.Employee", "Employee")
                        .WithMany("Permissions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("N5.Employees.Domain.Entities.PermissionType", "PermissionType")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PermissionType");
                });

            modelBuilder.Entity("N5.Employees.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("N5.Employees.Domain.Entities.PermissionType", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
